import { X, Copy, Download, Mail, QrCode, Link2, CheckCircle, Clock, Shield, FileText } from 'lucide-react'
import { useState, useMemo } from 'react'
import { QRCodeSVG } from 'qrcode.react'
import { jsPDF } from 'jspdf'

function ShareModal({ result, rawText, onClose, onCopy, copied }) {
  const [activeTab, setActiveTab] = useState('copy')
  const [linkGenerated, setLinkGenerated] = useState(false)
  const [generatedLink, setGeneratedLink] = useState('')
  const [showQR, setShowQR] = useState(false)

  // Generate shareable content
  const shareableText = useMemo(() => {
    return `Say It Better - Translation Summary
Generated: ${new Date().toLocaleString()}

SUMMARY:
${result.summary}

KEY THEMES:
${result.themes.map(t => `• ${t.theme}: ${t.description}`).join('\n')}

SHARE-READY VERSION:
"${result.share_ready}"

---
Generated by Say It Better - A communication aid for expressing thoughts clearly.
This is not therapy, diagnosis, or medical advice.`
  }, [result])

  // Generate a temporary encrypted link (simulated for demo)
  const generateSecureLink = () => {
    // In production, this would encrypt and upload to a secure backend
    // For demo, we create a data URL with base64 encoded content
    const encoded = btoa(encodeURIComponent(JSON.stringify({
      summary: result.summary,
      themes: result.themes,
      shareReady: result.share_ready,
      expires: Date.now() + 24 * 60 * 60 * 1000 // 24 hours
    })))
    
    // Simulated secure link (in production, this would be a real backend URL)
    const link = `${window.location.origin}/share/${encoded.slice(0, 20)}...`
    setGeneratedLink(link)
    setLinkGenerated(true)
  }

  // Generate PDF
  const generatePDF = () => {
    const doc = new jsPDF()
    const margin = 20
    const pageWidth = doc.internal.pageSize.getWidth()
    const contentWidth = pageWidth - margin * 2
    let y = margin

    // Header
    doc.setFillColor(20, 184, 166) // teal-500
    doc.rect(0, 0, pageWidth, 40, 'F')
    
    doc.setTextColor(255, 255, 255)
    doc.setFontSize(22)
    doc.setFont('helvetica', 'bold')
    doc.text('Say It Better', margin, 25)
    
    doc.setFontSize(10)
    doc.setFont('helvetica', 'normal')
    doc.text('Communication Summary', margin, 33)
    
    y = 55

    // Date
    doc.setTextColor(100, 116, 139) // soft-500
    doc.setFontSize(10)
    doc.text(`Generated: ${new Date().toLocaleString()}`, margin, y)
    y += 15

    // Summary Section
    doc.setTextColor(30, 41, 59) // soft-800
    doc.setFontSize(14)
    doc.setFont('helvetica', 'bold')
    doc.text('Clear Summary', margin, y)
    y += 8
    
    doc.setFontSize(11)
    doc.setFont('helvetica', 'normal')
    const summaryLines = doc.splitTextToSize(result.summary, contentWidth)
    doc.text(summaryLines, margin, y)
    y += summaryLines.length * 6 + 12

    // Themes Section
    doc.setFontSize(14)
    doc.setFont('helvetica', 'bold')
    doc.text('Key Themes', margin, y)
    y += 10
    
    doc.setFontSize(10)
    doc.setFont('helvetica', 'normal')
    result.themes.forEach((theme, index) => {
      doc.setFont('helvetica', 'bold')
      doc.text(`${index + 1}. ${theme.theme}`, margin + 5, y)
      y += 6
      doc.setFont('helvetica', 'normal')
      const descLines = doc.splitTextToSize(theme.description, contentWidth - 10)
      doc.text(descLines, margin + 10, y)
      y += descLines.length * 5 + 6
    })
    y += 5

    // Share-Ready Section
    doc.setFillColor(240, 253, 250) // teal-50
    doc.roundedRect(margin, y, contentWidth, 40, 3, 3, 'F')
    
    doc.setFontSize(12)
    doc.setFont('helvetica', 'bold')
    doc.setTextColor(15, 118, 110) // teal-700
    doc.text('Share-Ready Version', margin + 5, y + 10)
    
    doc.setFontSize(10)
    doc.setFont('helvetica', 'italic')
    const shareLines = doc.splitTextToSize(`"${result.share_ready}"`, contentWidth - 10)
    doc.text(shareLines, margin + 5, y + 20)
    y += 50

    // Footer disclaimer
    if (y > 250) {
      doc.addPage()
      y = margin
    }
    
    doc.setFillColor(254, 242, 242) // red-50
    doc.roundedRect(margin, y, contentWidth, 30, 3, 3, 'F')
    
    doc.setTextColor(185, 28, 28) // red-700
    doc.setFontSize(9)
    doc.setFont('helvetica', 'bold')
    doc.text('Important Notice', margin + 5, y + 10)
    doc.setFont('helvetica', 'normal')
    doc.text('This tool is a communication aid. It does not provide therapy, diagnosis, or medical advice.', margin + 5, y + 18)
    doc.text('Please discuss these observations with a qualified professional.', margin + 5, y + 24)

    // Save
    doc.save(`say-it-better-${new Date().toISOString().split('T')[0]}.pdf`)
  }

  // Open email client
  const openEmailDraft = () => {
    const subject = encodeURIComponent('My Say It Better Summary')
    const body = encodeURIComponent(shareableText)
    window.location.href = `mailto:?subject=${subject}&body=${body}`
  }

  const tabs = [
    { id: 'copy', label: 'Copy', icon: Copy },
    { id: 'pdf', label: 'PDF', icon: FileText },
    { id: 'email', label: 'Email', icon: Mail },
    { id: 'link', label: 'Secure Link', icon: Link2 },
  ]

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-soft-900/60 backdrop-blur-sm animate-fade-in">
      <div className="bg-white rounded-2xl shadow-2xl max-w-lg w-full max-h-[90vh] overflow-hidden animate-slide-up">
        {/* Header */}
        <div className="bg-gradient-to-r from-calm-500 to-calm-600 p-6 text-white">
          <div className="flex items-center justify-between">
            <div className="flex items-center gap-3">
              <Shield className="w-6 h-6" />
              <div>
                <h2 className="text-xl font-semibold">Share Your Summary</h2>
                <p className="text-calm-100 text-sm">Choose how you want to share</p>
              </div>
            </div>
            <button 
              onClick={onClose}
              className="p-2 hover:bg-white/20 rounded-lg transition-colors"
            >
              <X className="w-5 h-5" />
            </button>
          </div>
        </div>

        {/* Tab Navigation */}
        <div className="flex border-b border-soft-200">
          {tabs.map((tab) => (
            <button
              key={tab.id}
              onClick={() => setActiveTab(tab.id)}
              className={`flex-1 flex items-center justify-center gap-2 px-4 py-3 text-sm font-medium transition-colors ${
                activeTab === tab.id 
                  ? 'text-calm-600 border-b-2 border-calm-500 bg-calm-50' 
                  : 'text-soft-500 hover:text-soft-700 hover:bg-soft-50'
              }`}
            >
              <tab.icon className="w-4 h-4" />
              <span>{tab.label}</span>
            </button>
          ))}
        </div>

        {/* Tab Content */}
        <div className="p-6">
          {activeTab === 'copy' && (
            <div className="space-y-4">
              <p className="text-soft-600 text-sm">
                Copy your summary to paste anywhere — messages, notes, or documents.
              </p>
              <div className="bg-soft-50 rounded-xl p-4 max-h-48 overflow-y-auto">
                <pre className="text-xs text-soft-700 whitespace-pre-wrap font-mono">
                  {shareableText}
                </pre>
              </div>
              <button
                onClick={() => onCopy(shareableText)}
                className="w-full flex items-center justify-center gap-2 px-4 py-3 bg-calm-500 text-white rounded-xl hover:bg-calm-600 transition-colors"
              >
                {copied ? <CheckCircle className="w-5 h-5" /> : <Copy className="w-5 h-5" />}
                <span>{copied ? 'Copied!' : 'Copy to Clipboard'}</span>
              </button>
            </div>
          )}

          {activeTab === 'pdf' && (
            <div className="space-y-4">
              <p className="text-soft-600 text-sm">
                Generate a professionally formatted PDF to share with your therapist, doctor, or print for your records.
              </p>
              <div className="bg-soft-50 rounded-xl p-6 text-center">
                <FileText className="w-12 h-12 text-calm-500 mx-auto mb-3" />
                <p className="text-soft-700 font-medium">Professional PDF Document</p>
                <p className="text-soft-500 text-sm">Includes summary, themes, and share-ready version</p>
              </div>
              <button
                onClick={generatePDF}
                className="w-full flex items-center justify-center gap-2 px-4 py-3 bg-calm-500 text-white rounded-xl hover:bg-calm-600 transition-colors"
              >
                <Download className="w-5 h-5" />
                <span>Download PDF</span>
              </button>
            </div>
          )}

          {activeTab === 'email' && (
            <div className="space-y-4">
              <p className="text-soft-600 text-sm">
                Open a pre-filled email draft in your default email app. You control who receives it.
              </p>
              <div className="bg-soft-50 rounded-xl p-4">
                <div className="flex items-start gap-3">
                  <Mail className="w-5 h-5 text-soft-400 flex-shrink-0 mt-0.5" />
                  <div>
                    <p className="text-soft-700 font-medium text-sm">Subject: My Say It Better Summary</p>
                    <p className="text-soft-500 text-xs mt-1">
                      Body will include your summary, themes, and share-ready version
                    </p>
                  </div>
                </div>
              </div>
              <button
                onClick={openEmailDraft}
                className="w-full flex items-center justify-center gap-2 px-4 py-3 bg-calm-500 text-white rounded-xl hover:bg-calm-600 transition-colors"
              >
                <Mail className="w-5 h-5" />
                <span>Open Email Draft</span>
              </button>
              <p className="text-xs text-soft-400 text-center">
                Opens your default email app — nothing is sent automatically
              </p>
            </div>
          )}

          {activeTab === 'link' && (
            <div className="space-y-4">
              <p className="text-soft-600 text-sm">
                Generate a secure, temporary link that expires in 24 hours. Perfect for sharing in person.
              </p>
              
              {!linkGenerated ? (
                <>
                  <div className="bg-amber-50 border border-amber-200 rounded-xl p-4 flex items-start gap-3">
                    <Clock className="w-5 h-5 text-amber-600 flex-shrink-0" />
                    <div>
                      <p className="text-amber-800 font-medium text-sm">Temporary & Private</p>
                      <p className="text-amber-700 text-xs mt-1">
                        Link auto-expires after 24 hours. Data is encrypted client-side.
                      </p>
                    </div>
                  </div>
                  <button
                    onClick={generateSecureLink}
                    className="w-full flex items-center justify-center gap-2 px-4 py-3 bg-calm-500 text-white rounded-xl hover:bg-calm-600 transition-colors"
                  >
                    <Link2 className="w-5 h-5" />
                    <span>Generate Secure Link</span>
                  </button>
                </>
              ) : (
                <>
                  <div className="bg-green-50 border border-green-200 rounded-xl p-4">
                    <p className="text-green-800 font-medium text-sm mb-2 flex items-center gap-2">
                      <CheckCircle className="w-4 h-4" />
                      Link Generated!
                    </p>
                    <p className="text-xs text-green-700 font-mono bg-green-100 p-2 rounded break-all">
                      {generatedLink}
                    </p>
                    <p className="text-xs text-green-600 mt-2 flex items-center gap-1">
                      <Clock className="w-3 h-3" />
                      Expires in 24 hours
                    </p>
                  </div>
                  
                  <button
                    onClick={() => setShowQR(!showQR)}
                    className="w-full flex items-center justify-center gap-2 px-4 py-2 bg-soft-100 text-soft-700 rounded-xl hover:bg-soft-200 transition-colors"
                  >
                    <QrCode className="w-4 h-4" />
                    <span>{showQR ? 'Hide' : 'Show'} QR Code</span>
                  </button>
                  
                  {showQR && (
                    <div className="flex justify-center p-4 bg-white border border-soft-200 rounded-xl">
                      <QRCodeSVG 
                        value={generatedLink} 
                        size={180}
                        level="M"
                        includeMargin
                      />
                    </div>
                  )}
                  
                  <button
                    onClick={() => onCopy(generatedLink)}
                    className="w-full flex items-center justify-center gap-2 px-4 py-3 bg-calm-500 text-white rounded-xl hover:bg-calm-600 transition-colors"
                  >
                    {copied ? <CheckCircle className="w-5 h-5" /> : <Copy className="w-5 h-5" />}
                    <span>{copied ? 'Copied!' : 'Copy Link'}</span>
                  </button>
                </>
              )}
            </div>
          )}
        </div>

        {/* Privacy Notice */}
        <div className="px-6 pb-6">
          <div className="bg-soft-50 border border-soft-200 rounded-xl p-3 flex items-start gap-2">
            <Shield className="w-4 h-4 text-soft-500 flex-shrink-0 mt-0.5" />
            <p className="text-xs text-soft-600">
              You're in control. All sharing is manual — we never send your data anywhere automatically.
            </p>
          </div>
        </div>
      </div>
    </div>
  )
}

export default ShareModal
