import { X, Copy, Download, Mail, QrCode, Link2, CheckCircle, Clock, Shield, FileText } from 'lucide-react'
import { useState, useMemo } from 'react'
import { QRCodeSVG } from 'qrcode.react'
import { jsPDF } from 'jspdf'
import { generateKey, exportKey, encrypt } from '../services/crypto'

// In development, uses localhost:8000. In production (Vercel), API is at /api
const API_BASE = import.meta.env.VITE_API_BASE || '/api'

function ShareModal({ result, rawText, onClose, onCopy, copied }) {
  const [activeTab, setActiveTab] = useState('copy')
  const [linkGenerated, setLinkGenerated] = useState(false)
  const [generatedLink, setGeneratedLink] = useState('')
  const [showQR, setShowQR] = useState(false)

  // Generate shareable content
  const shareableText = useMemo(() => {
    return `Say It Better - Translation Summary
Generated: ${new Date().toLocaleString()}

SUMMARY:
${result.summary}

KEY THEMES:
${result.themes.map(t => `• ${t.theme}: ${t.description}`).join('\n')}

SHARE - READY VERSION:
"${result.share_ready}"

---
  Generated by Say It Better - A communication aid for expressing thoughts clearly.
This is not therapy, diagnosis, or medical advice.`
  }, [result])

  // Generate a temporary encrypted link (Zero-Knowledge)
  const generateSecureLink = async () => {
    try {
      // 1. Generate a random key (AES-GCM 256)
      const key = await generateKey()

      // 2. Encrypt the data
      const payload = {
        summary: result.summary,
        themes: result.themes,
        share_ready: result.share_ready,
        created_at: Date.now()
      }

      const { encrypted_data, iv } = await encrypt(payload, key)

      // 3. Upload encrypted blob to server (Server CANNOT read this)
      const response = await fetch(`${API_BASE}/share`, {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json'
        },
        body: JSON.stringify({
          encrypted_data,
          iv
        })
      })

      if (!response.ok) {
        throw new Error('Failed to upload shared data')
      }

      const { share_id } = await response.json()

      // 4. Construct URL with ID (query) and Key (hash)
      // The key is in the hash, so it isn't sent to the server in the request
      const exportedKey = await exportKey(key)
      const link = `${window.location.origin}/?share_id=${share_id}#key=${exportedKey}`

      setGeneratedLink(link)
      setLinkGenerated(true)
    } catch (err) {
      console.error('Failed to generate secure link:', err)
      alert('Could not generate secure link. Please try again.')
    }
  }

  // Generate PDF
  const generatePDF = () => {
    try {
      const doc = new jsPDF()
      const margin = 20
      const pageWidth = doc.internal.pageSize.getWidth()
      const contentWidth = pageWidth - margin * 2
      let y = margin

      // Header
      doc.setFillColor(20, 184, 166) // teal-500
      doc.rect(0, 0, pageWidth, 40, 'F')

      doc.setTextColor(255, 255, 255)
      doc.setFontSize(22)
      doc.setFont('helvetica', 'bold')
      doc.text('Say It Better', margin, 25)

      doc.setFontSize(10)
      doc.setFont('helvetica', 'normal')
      doc.text('Communication Summary', margin, 33)

      y = 55

      // Date
      doc.setTextColor(100, 116, 139) // soft-500
      doc.setFontSize(10)
      doc.text(`Generated: ${new Date().toLocaleString()}`, margin, y)
      y += 15

      // Summary Section
      doc.setTextColor(30, 41, 59) // soft-800
      doc.setFontSize(14)
      doc.setFont('helvetica', 'bold')
      doc.text('Clear Summary', margin, y)
      y += 8

      doc.setFontSize(11)
      doc.setFont('helvetica', 'normal')
      const summaryLines = doc.splitTextToSize(result.summary, contentWidth)
      doc.text(summaryLines, margin, y)
      y += summaryLines.length * 6 + 12

      // Themes Section
      doc.setFontSize(14)
      doc.setFont('helvetica', 'bold')
      doc.text('Key Themes', margin, y)
      y += 10

      doc.setFontSize(10)
      doc.setFont('helvetica', 'normal')
      result.themes.forEach((theme, index) => {
        doc.setFont('helvetica', 'bold')
        doc.text(`${index + 1}. ${theme.theme}`, margin + 5, y)
        y += 6
        doc.setFont('helvetica', 'normal')
        const descLines = doc.splitTextToSize(theme.description, contentWidth - 10)
        doc.text(descLines, margin + 10, y)
        y += descLines.length * 5 + 6
      })
      y += 5

      // Share-Ready Section
      doc.setFillColor(240, 253, 250) // teal-50
      doc.roundedRect(margin, y, contentWidth, 40, 3, 3, 'F')

      doc.setFontSize(12)
      doc.setFont('helvetica', 'bold')
      doc.setTextColor(15, 118, 110) // teal-700
      doc.text('Share-Ready Version', margin + 5, y + 10)

      doc.setFontSize(10)
      doc.setFont('helvetica', 'italic')
      const shareLines = doc.splitTextToSize(`"${result.share_ready}"`, contentWidth - 10)
      doc.text(shareLines, margin + 5, y + 20)
      y += 50

      // Footer disclaimer
      if (y > 250) {
        doc.addPage()
        y = margin
      }

      doc.setFillColor(254, 242, 242) // red-50
      doc.roundedRect(margin, y, contentWidth, 30, 3, 3, 'F')

      doc.setTextColor(185, 28, 28) // red-700
      doc.setFontSize(9)
      doc.setFont('helvetica', 'bold')
      doc.text('Important Notice', margin + 5, y + 10)
      doc.setFont('helvetica', 'normal')
      doc.text('This tool is a communication aid. It does not provide therapy, diagnosis, or medical advice.', margin + 5, y + 18)
      doc.text('Please discuss these observations with a qualified professional.', margin + 5, y + 24)

      // Save
      doc.save(`say-it-better-${new Date().toISOString().split('T')[0]}.pdf`)
    } catch (e) {
      console.error('PDF Generation Error:', e)
      alert('Failed to generate PDF. Please try again.')
    }
  }

  // Open email client
  const openEmailDraft = () => {
    const subject = encodeURIComponent('My Say It Better Summary')
    // Truncate to avoid URL length limits
    const bodyText = shareableText.length > 1500
      ? shareableText.slice(0, 1500) + '...\n(Content truncated for email)'
      : shareableText
    const body = encodeURIComponent(bodyText)
    window.open(`mailto:?subject=${subject}&body=${body}`, '_blank')
  }

  const tabs = [
    { id: 'copy', label: 'Copy', icon: Copy },
    { id: 'pdf', label: 'PDF', icon: FileText },
    { id: 'email', label: 'Email', icon: Mail },
    { id: 'link', label: 'Secure Link', icon: Link2 },
  ]

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-[#2d3436]/80 backdrop-blur-sm animate-fade-in">
      <div className="bg-white border-4 border-[#2d3436] shadow-[8px_8px_0px_0px_#2d3436] max-w-lg w-full max-h-[90vh] overflow-hidden">
        {/* Header */}
        <div className="bg-[#2d3436] p-6 text-white">
          <div className="flex items-center justify-between">
            <div className="flex items-center gap-3">
              <div className="w-10 h-10 bg-[#14B8A6] border-2 border-white flex items-center justify-center">
                <Shield className="w-5 h-5" />
              </div>
              <div>
                <h2 className="text-xl font-black uppercase tracking-wider">Share Your Summary</h2>
                <p className="text-[#5eead4] text-sm font-medium">Choose how you want to share</p>
              </div>
            </div>
            <button
              onClick={onClose}
              className="p-2 hover:bg-white/20 border-2 border-white/30 transition-colors"
            >
              <X className="w-5 h-5" />
            </button>
          </div>
        </div>

        {/* Tab Navigation */}
        <div className="flex border-b-4 border-[#2d3436]">
          {tabs.map((tab) => (
            <button
              key={tab.id}
              onClick={() => setActiveTab(tab.id)}
              className={`flex-1 flex items-center justify-center gap-2 px-4 py-3 text-sm font-bold uppercase tracking-wide transition-colors ${activeTab === tab.id
                ? 'text-white bg-[#14B8A6] border-b-4 border-[#0d9488]'
                : 'text-[#2d3436] hover:bg-[#14B8A6]/10'
                }`}
            >
              <tab.icon className="w-4 h-4" />
              <span>{tab.label}</span>
            </button>
          ))}
        </div>

        {/* Tab Content */}
        <div className="p-6">
          {activeTab === 'copy' && (
            <div className="space-y-4">
              <p className="text-[#636e72] text-sm font-medium">
                Copy your summary to paste anywhere - messages, notes, or documents.
              </p>
              <div className="bg-[#f8f9fa] border-2 border-[#2d3436] p-4 max-h-48 overflow-y-auto">
                <pre className="text-xs text-[#2d3436] whitespace-pre-wrap font-mono">
                  {shareableText}
                </pre>
              </div>
              <button
                onClick={() => onCopy(shareableText)}
                className="w-full flex items-center justify-center gap-2 px-4 py-3 bg-[#14B8A6] text-white font-bold uppercase tracking-wide border-4 border-[#2d3436] shadow-[4px_4px_0px_0px_#2d3436] hover:shadow-[2px_2px_0px_0px_#2d3436] hover:translate-x-[2px] hover:translate-y-[2px] transition-all"
              >
                {copied ? <CheckCircle className="w-5 h-5" /> : <Copy className="w-5 h-5" />}
                <span>{copied ? 'Copied!' : 'Copy to Clipboard'}</span>
              </button>
            </div>
          )}

          {activeTab === 'pdf' && (
            <div className="space-y-4">
              <p className="text-[#636e72] text-sm font-medium">
                Generate a professionally formatted PDF to share with your therapist, doctor, or print for your records.
              </p>
              <div className="bg-[#f8f9fa] border-2 border-[#2d3436] p-6 text-center">
                <FileText className="w-12 h-12 text-[#14B8A6] mx-auto mb-3" />
                <p className="text-[#2d3436] font-bold">Professional PDF Document</p>
                <p className="text-[#636e72] text-sm">Includes summary, themes, and share-ready version</p>
              </div>
              <button
                onClick={generatePDF}
                className="w-full flex items-center justify-center gap-2 px-4 py-3 bg-[#14B8A6] text-white font-bold uppercase tracking-wide border-4 border-[#2d3436] shadow-[4px_4px_0px_0px_#2d3436] hover:shadow-[2px_2px_0px_0px_#2d3436] hover:translate-x-[2px] hover:translate-y-[2px] transition-all"
              >
                <Download className="w-5 h-5" />
                <span>Download PDF</span>
              </button>
            </div>
          )}

          {activeTab === 'email' && (
            <div className="space-y-4">
              <p className="text-[#636e72] text-sm font-medium">
                Open a pre-filled email draft in your default email app. You control who receives it.
              </p>
              <div className="bg-[#f8f9fa] border-2 border-[#2d3436] p-4">
                <div className="flex items-start gap-3">
                  <Mail className="w-5 h-5 text-[#14B8A6] flex-shrink-0 mt-0.5" />
                  <div>
                    <p className="text-[#2d3436] font-bold text-sm">Subject: My Say It Better Summary</p>
                    <p className="text-[#636e72] text-xs mt-1">
                      Body will include your summary, themes, and share-ready version
                    </p>
                  </div>
                </div>
              </div>
              <button
                onClick={openEmailDraft}
                className="w-full flex items-center justify-center gap-2 px-4 py-3 bg-[#14B8A6] text-white font-bold uppercase tracking-wide border-4 border-[#2d3436] shadow-[4px_4px_0px_0px_#2d3436] hover:shadow-[2px_2px_0px_0px_#2d3436] hover:translate-x-[2px] hover:translate-y-[2px] transition-all"
              >
                <Mail className="w-5 h-5" />
                <span>Open Email Draft</span>
              </button>
              <p className="text-xs text-[#636e72] text-center font-medium">
                Opens your default email app - nothing is sent automatically
              </p>
            </div>
          )}

          {activeTab === 'link' && (
            <div className="space-y-4">
              <p className="text-[#636e72] text-sm font-medium">
                Generate a secure, temporary link that expires in 24 hours. Perfect for sharing in person.
              </p>

              {!linkGenerated ? (
                <>
                  <div className="bg-[#f39c12]/10 border-2 border-[#f39c12] p-4 flex items-start gap-3">
                    <Clock className="w-5 h-5 text-[#f39c12] flex-shrink-0" />
                    <div>
                      <p className="text-[#2d3436] font-bold text-sm">Temporary & Private</p>
                      <p className="text-[#636e72] text-xs mt-1">
                        Link auto-expires after 24 hours. Data is encrypted on your device - even we can't read it.
                      </p>
                    </div>
                  </div>
                  <button
                    onClick={generateSecureLink}
                    className="w-full flex items-center justify-center gap-2 px-4 py-3 bg-[#14B8A6] text-white font-bold uppercase tracking-wide border-4 border-[#2d3436] shadow-[4px_4px_0px_0px_#2d3436] hover:shadow-[2px_2px_0px_0px_#2d3436] hover:translate-x-[2px] hover:translate-y-[2px] transition-all"
                  >
                    <Link2 className="w-5 h-5" />
                    <span>Generate Secure Link</span>
                  </button>
                </>
              ) : (
                <>
                  <div className="bg-[#14B8A6]/10 border-2 border-[#14B8A6] p-4">
                    <p className="text-[#2d3436] font-bold text-sm mb-2 flex items-center gap-2">
                      <CheckCircle className="w-4 h-4 text-[#14B8A6]" />
                      Link Generated!
                    </p>
                    <p className="text-xs text-[#2d3436] font-mono bg-white p-2 border border-[#2d3436] break-all">
                      {generatedLink}
                    </p>
                    <p className="text-xs text-[#636e72] mt-2 flex items-center gap-1 font-medium">
                      <Clock className="w-3 h-3" />
                      Expires in 24 hours
                    </p>
                  </div>

                  <button
                    onClick={() => setShowQR(!showQR)}
                    className="w-full flex items-center justify-center gap-2 px-4 py-2 bg-[#f8f9fa] text-[#2d3436] border-2 border-[#2d3436] font-bold hover:bg-[#e9ecef] transition-colors"
                  >
                    <QrCode className="w-4 h-4" />
                    <span>{showQR ? 'Hide' : 'Show'} QR Code</span>
                  </button>

                  {showQR && (
                    <div className="flex justify-center p-4 bg-white border-2 border-[#2d3436]">
                      <QRCodeSVG
                        value={generatedLink}
                        size={180}
                        level="M"
                        includeMargin
                      />
                    </div>
                  )}

                  <button
                    onClick={() => onCopy(generatedLink)}
                    className="w-full flex items-center justify-center gap-2 px-4 py-3 bg-[#14B8A6] text-white font-bold uppercase tracking-wide border-4 border-[#2d3436] shadow-[4px_4px_0px_0px_#2d3436] hover:shadow-[2px_2px_0px_0px_#2d3436] hover:translate-x-[2px] hover:translate-y-[2px] transition-all"
                  >
                    {copied ? <CheckCircle className="w-5 h-5" /> : <Copy className="w-5 h-5" />}
                    <span>{copied ? 'Copied!' : 'Copy Link'}</span>
                  </button>
                </>
              )}
            </div>
          )}
        </div>

        {/* Privacy Notice */}
        <div className="px-6 pb-6">
          <div className="bg-[#f8f9fa] border-2 border-[#2d3436] p-3 flex items-start gap-2">
            <Shield className="w-4 h-4 text-[#14B8A6] flex-shrink-0 mt-0.5" />
            <p className="text-xs text-[#636e72] font-medium">
              You're in control. All sharing is manual - we never send your data anywhere automatically.
            </p>
          </div>
        </div>
      </div>
    </div>
  )
}

export default ShareModal
